#!/usr/bin/env python

import json
import os
import sys
import urllib

if __name__ == '__main__':

    try:
        request_name = sys.argv[1]
        factory_etc  = sys.argv[2]
    except IndexError:
        print 'Use: ' + sys.argv[0] + ' name_of_request  apf_etc_dir'
        sys.exit(1)

    request = {}
    request[request_name] = {}

    request[request_name]['action'] = 'spawn'

    request[request_name]['services'] = {}

    # define a cctools catalog server
    wq = {}

    wq['version'] = '6.0.0'
    wq['action']  = 'spawn'
    wq['command'] = 'vc3-cctools-catalog-server --requestid "$VC3_REQUESTID" --port-file "$VC3_REQUESTID_RUNTIME_DIR/cctools-catalog-server-port" -- -dall -o "$VC3_REQUESTID_LOG_DIR/cctools-catalog-server.log" --history="$VC3_REQUESTID_LOG_DIR/cctools-catalog-server.history"'

    request[request_name]['services']['cctools-catalog-server'] = wq

    # define a pilot factory
    ft = {} 
    def_clu  = '$VC3_REQUESTID_RUNTIME_DIR/runtime.conf'
    dest_etc = '$VC3_REQUESTID_RUNTIME_DIR/vc3-factory/etc'

    ft['version'] = '0.0.1'
    ft['action']  = 'spawn'
    ft['command'] = 'autopyfactory --debug --console --conf=%s,%s/vc3_factory.conf' % (def_clu,dest_etc)

    ft['files']   = {}

    for name in ['vc3_factory.conf', 'mappings.conf', 'monitor.conf', 'vc3_queues.conf']:
        filename = os.path.join(factory_etc, name)

        with open(filename, 'r') as f:
            all_the_file = f.read()
	    
	    if name is 'vc3_queues.conf':
		all_the_file += """
[VC3_WQ_MASTER]
enabled = True
workqueue.mastername = %s

""" % (request_name,)
		
            encoded_file = urllib.quote_plus(all_the_file)


            ft['files'][name] = {}
            ft['files'][name]['destination'] = os.path.join(dest_etc, name)
            ft['files'][name]['contents']    = encoded_file

    request[request_name]['services']['vc3-factory'] = ft

    requests = { 'request' : request }
    print json.dumps(requests, indent = 4)

